-- Supabase SQL Editor setup script for the NLP Assistant project.
-- Run this in your Supabase project's SQL Editor.

create table if not exists public.chats (
    id bigint generated by default as identity primary key,
    user_message text not null,
    bot_response text not null,
    tokens jsonb not null default '[]'::jsonb,
    keywords jsonb not null default '[]'::jsonb,
    sentiment varchar(20) not null,
    sentiment_score numeric(6, 3) not null,
    classification varchar(50) not null,
    entities jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.chats enable row level security;

drop policy if exists "Allow project API inserts" on public.chats;
drop policy if exists "Allow project API reads" on public.chats;
drop policy if exists "Allow project API deletes" on public.chats;

create policy "Allow project API inserts"
on public.chats
for insert
to anon
with check (true);

create policy "Allow project API reads"
on public.chats
for select
to anon
using (true);

create policy "Allow project API deletes"
on public.chats
for delete
to anon
using (true);

insert into public.chats (
    user_message,
    bot_response,
    tokens,
    keywords,
    sentiment,
    sentiment_score,
    classification,
    entities
) values (
    'I love this NLP chatbot because it is helpful',
    'That sounds positive. I extracted the important terms for review.',
    '["I", "love", "this", "NLP", "chatbot", "because", "it", "is", "helpful"]'::jsonb,
    '["love", "nlp", "chatbot", "helpful"]'::jsonb,
    'Positive',
    0.850,
    'Feedback',
    '[]'::jsonb
);
