-- Supabase SQL Editor setup script for the NoteAI Lessons project.
-- Run this in your Supabase project's SQL Editor.

create table if not exists public.notes (
    id bigint generated by default as identity primary key,
    title text not null default 'Untitled Note',
    content text not null,
    tokens jsonb not null default '[]'::jsonb,
    lemmas jsonb not null default '[]'::jsonb,
    keywords jsonb not null default '[]'::jsonb,
    sentiment varchar(20) not null,
    sentiment_score numeric(6, 3) not null,
    classification varchar(50) not null,
    entities jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.assistant_chats (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    query_tokens jsonb not null default '[]'::jsonb,
    query_keywords jsonb not null default '[]'::jsonb,
    matched_note_ids jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.notes enable row level security;
alter table public.assistant_chats enable row level security;

drop policy if exists "Allow note inserts" on public.notes;
drop policy if exists "Allow note reads" on public.notes;
drop policy if exists "Allow note deletes" on public.notes;
drop policy if exists "Allow chat inserts" on public.assistant_chats;
drop policy if exists "Allow chat reads" on public.assistant_chats;
drop policy if exists "Allow chat deletes" on public.assistant_chats;

create policy "Allow note inserts"
on public.notes
for insert
to anon
with check (true);

create policy "Allow note reads"
on public.notes
for select
to anon
using (true);

create policy "Allow note deletes"
on public.notes
for delete
to anon
using (true);

create policy "Allow chat inserts"
on public.assistant_chats
for insert
to anon
with check (true);

create policy "Allow chat reads"
on public.assistant_chats
for select
to anon
using (true);

create policy "Allow chat deletes"
on public.assistant_chats
for delete
to anon
using (true);

insert into public.notes (
    title,
    content,
    tokens,
    lemmas,
    keywords,
    sentiment,
    sentiment_score,
    classification,
    entities
) values (
    'Software Implementation Lesson',
    'Software implementation includes user training, data migration, system testing, and final cutover.',
    '["Software", "implementation", "includes", "user", "training", "data", "migration", "system", "testing", "and", "final", "cutover"]'::jsonb,
    '["software", "implementation", "include", "user", "training", "data", "migration", "system", "testing", "final", "cutover"]'::jsonb,
    '["software", "implementation", "training", "data", "migration", "system", "testing", "cutover"]'::jsonb,
    'Neutral',
    0.000,
    'General Message',
    '[]'::jsonb
);
